fragment Content on DraftIssue {
   title
}

fragment Select on ProjectV2ItemFieldSingleSelectValue {
   name
   optionId
}

fragment Text on ProjectV2ItemFieldTextValue {
   text
}

fragment Field on ProjectV2ItemFieldValue {
   ...Text
   ...Select
}

fragment Item on ProjectV2Item {
   id
   content {
      __typename
      ...Content
   }
   status: fieldValueByName(name: "Status") {
      __typename
      ...Field
   }
   type: fieldValueByName(name: "Type") {
      __typename
      ...Field
   }
   size: fieldValueByName(name: "Size") {
      __typename
      ...Field
   }
   link: fieldValueByName(name: "Link") {
      __typename
      ...Field
   }
}

fragment Project on ProjectV2 {
   title
   items(first: 100) {
      totalCount
      nodes {
         ...Item
      }
   }
}

query getProjects {
   viewer {
      projectV2(number: 10) {
         ...Project
      }
   }
}

query getActiveProjects {
   viewer {
      projectV2(number: 10) {
         ...Project
      }
   }
}
