name: Test

on:
   push:
      branches:
         - main
      paths-ignore:
         - profile/**

jobs:
   test:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v7

         - name: Cache node modules
           id: cache-npm
           uses: actions/cache@v6
           with:
              path: ~/.npm
              key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-node-modules-

         - run: yarn install

         - run: yarn test
