name: Test

on: [push]

jobs:
   test:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: Cache node modules
           id: cache-npm
           uses: actions/cache@v3
           with:
              path: ~/.npm
              key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                 ${{ runner.os }}-node-modules-

         - run: yarn install

         - run: yarn test
