name: Test
on:
   pull_request:
      types: [opened, synchronize]
   push:
      branches: [main]

jobs:
   test:
      permissions:
         contents: read
         packages: read

      runs-on: ubuntu-20.04
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0

         - uses: pnpm/action-setup@v4
           with:
              run_install: |
                 - recursive: true
                   args: [--frozen-lockfile, --strict-peer-dependencies]

         - uses: actions/setup-node@v4
           with:
              node-version: 16
              cache: pnpm

         - run: pnpm run test

         - name: notify sonarqube
           if: ${{ github.event_name == 'push' }}
           uses: sonarsource/sonarqube-scan-action@master
           env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
